version: "2"
services:
# ftp:
#   container_name: ftp
#   image: librairy/ftp:1.0
#   restart: always
#   ports:
#     - "5051:21"
#   volumes:
#     - ./data:/home/ftpusers/librairy
 harvester:
   container_name: harvester
   image: librairy/harvester-research:latest
   #restart: always
   volumes:
       - ./data:/librairy/files
   external_links:
       - column-db
       - document-db
       - graph-db
       - event-bus
   networks:
       - "db"
       - "events"
networks:
  db:
    external:
      name: base_db
  events:
    external:
      name: base_events
